Bugfix. Make sure URLs are unescaped
Otherwise the % signs interferes with variable interpolation in python's
logging module.

Causes this error:
    TypeError: float argument required, not dict
    Traceback (most recent call last):
    File "/usr/lib/python2.6/logging/__init__.py", line 776, in emit
        msg = self.format(record)
    File "/usr/lib/python2.6/logging/__init__.py", line 654, in format
        return fmt.format(record)
    File "/usr/lib/python2.6/logging/__init__.py", line 436, in format
        record.message = record.getMessage()
    File "/usr/lib/python2.6/logging/__init__.py", line 306, in getMessage
        msg = msg % self.args